### ISSUE TITLE
Feature request: edit/remove flixs

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/makemyflix#12]
Making flix is trial and error. Currently there is no functionality to edit your configuration, overwritting flix (base on the name) seems not possible either (when using an already "taken" name, the API throws an error with is not shown in the UI). So whilst trying to get Goudse straten available als flix there are now several configurations, each with another name (gtm1 gtm2 gtm3 gtm4 ... and I started with Goudse straten op beeld which I really like but that configuration was faulty and I can't remove that one). 

Maybe to stay away from user management, the dialog after creating a flix might show a key (eg. SHA256 of config) which a user can use to remove or edit that flix.

**Comment by EnnoMeijers** [comment]
As far as I see the edit functionality is still only available in the strapi admin console. The original request was the option for regular users (without access to the admin console) to edit their flix through the Nuxt front-end. With the generated hash key they should be able to recall and edit their original configuration. I will reopen this issue to discuss the functionality in more detail.

**Comment by aabelmann** [comment]
@EnnoMeijers Sorry I am a bit confused by your answer, you state that edit functionality is only available in the strapi admin console but also state that users can use the generated hash key to recall and edit their original configuration.

I can tell you even an regular user can create a Flix, get the token in the url and use said token to edit the flix after  it was published. Are there issues with this functionality?

**Comment by EnnoMeijers** [comment]
Ok, I probably misunderstood the functionality! Can you tell me how a regular user can edit the flix through that was created and how the token is communicated after creation? This is not documented as far as I see.

**Comment by aabelmann** [comment]
It's not communicated explcitily, the token just lives in the url.
We assumed that most people will use bookmarks or copy the url.
This alone is enough to be able to edit later on

**Comment by EnnoMeijers** [comment]
Ok, it is clear to me now how it works, I will close the issue after updating the documentation.

**Comment by EnnoMeijers** [comment]
Updated the documentation for the edit functionality, closing this issue
