### ISSUE TITLE
Use IIIF scaling options for result page

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/makemyflix#29]
IIF scaling options should be used to generate thumbnails for the result page. Large images are currently loaded very slow when many are displayed on the result page. In the map section for the UVA-Beeldbank example (see https://github.com/netwerk-digitaal-erfgoed/makemyflix-configs/tree/main/UVA-Beeldbank) a 390 px image is generated from a 40Mb image. IIIF offers smart ways to optimize this (f.e. replace "full/full" with "full/390,")

**Comment by aabelmann** [comment]
@EnnoMeijers Good find, the code is basically checking if we should support IIIF or not, but also if the url is an IIIF url.
In the later situation I should change my sizes to the new situation, which I wasn't doing yet.
