### ISSUE TITLE
Configuring a new flix fails

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/makemyflix#8]
When trying to configure a new Flix it fails after the first screen with the following error in the console:

Error saving flix: FetchError: [POST] "https://makemyflix.netwerkdigitaalerfgoed.nl/admin/flixes": 405 
    at async o (sc1t6A6d.js:18:20101)
    at async c (sc1t6A6d.js:26:6780)
    at async Proxy.d (sc1t6A6d.js:26:8171)
    at async B9dmTgo5.js:1:12719
c @ sc1t6A6d.js:26

**Comment by SVis760** [comment]
Also encountered an error when using the UI to configure a new flix, here an example of a standard flix config that did not render results:

[example config used](https://github.com/netwerk-digitaal-erfgoed/heritageflix-configs/blob/main/paintings/queries.json)
*tried also without LIMIT _LIMIT_ and fixing the Bind(<_CATEGORYID_>), however no match yield results
![makemyflix-config](https://github.com/user-attachments/assets/4e19e6c6-a310-423a-b714-097a97261039)
![makemyflix-error](https://github.com/user-attachments/assets/ebadf8b6-73b2-4d67-85fa-cc1399c87d15)

**Comment by EnnoMeijers** [comment]
Fixed
